name: BrudilnikIOS
options:
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.0"

targets:
  BrudilnikIOS:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - .github
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.brudilnik
        INFOPLIST_FILE: Info.plist
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: Brudilnik
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
